name: Build and Release APK
on:
  push:
    tags: ['v*']
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('android/gradle/wrapper/gradle-wrapper.properties', 'android/build.gradle.kts', 'android/app/build.gradle.kts', 'android/settings.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
      - run: flutter pub get
      - run: flutter build apk --flavor prod --release --dart-define=RELEASE=true --dart-define=BACKEND_URL=https://hdapp-537407794596.europe-west1.run.app
      - uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-prod-release.apk
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GH_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}