name: Build and Release APK
on:
  push:
    tags: ['v*']  # Trigger on version tags like v1.0.0
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
      - run: flutter pub get
      - run: flutter build apk --flavor prod --release --dart-define=RELEASE=true
      - uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GH_TOKEN }}  # Use the PAT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
      - run: flutter pub get
      - run: flutter build ios --flavor prod --release --dart-define=RELEASE=true --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          name: release-ios
          path: build/ios/iphoneos/Runner.app